#!/bin/zsh
# shellcheck shell=bash disable=SC2296
# Check if a C feature (header, function, or type) exists on macOS
# Usage: ./check-feature.zsh <feature>
# Examples:
#   ./check-feature.zsh wchar.h
#   ./check-feature.zsh setrlimit
#   ./check-feature.zsh pid_t
#   ./check-feature.zsh _CS_PATH
# DISCLAIMER: This script was generated by AI so I can focus on the actual work

set -uo pipefail

if [[ $# -eq 0 ]]; then
    echo "Usage: $0 <header.h | function | type | constant>"
    exit 1
fi

feature="$1"
sdk=$(xcrun --show-sdk-path 2>/dev/null)
cc=${CC:-cc}
tmp=$(mktemp /tmp/check-feature.XXXXXX.c)
trap "rm -f $tmp ${tmp%.c}.out" EXIT

# Detect if input looks like a header
if [[ "$feature" == *.h ]]; then
    echo "Checking header: $feature"

    # Check in SDK include path
    found=$(find "$sdk/usr/include" -name "$feature" 2>/dev/null | head -5)
    if [[ -n "$found" ]]; then
        echo "  FOUND in SDK:"
        echo "$found" | sed 's/^/    /'
    fi

    # Try to compile
    cat > "$tmp" <<EOF
#include <$feature>
int main(void) { return 0; }
EOF
    if $cc -fsyntax-only "$tmp" 2>/dev/null; then
        echo "  COMPILABLE: yes"
    else
        echo "  COMPILABLE: no"
    fi

    # Check man page for standards conformance
    section=$(man -w "$feature" 2>/dev/null && echo "found" || echo "")
    if [[ -n "$section" ]]; then
        echo "  STANDARDS:"
        man "$feature" 2>/dev/null | col -b | grep -iE '(conforming|standard|posix|ansi|iso|ieee|c[0-9]{2}|c1[0-9])' | head -5 | sed 's/^/    /'
    fi
else
    echo "Checking symbol: $feature"

    # Grep SDK headers for the symbol
    echo "  SDK HEADER SEARCH:"
    sdk_matches=$(grep -rl --include='*.h' "\b${feature}\b" "$sdk/usr/include/" 2>/dev/null | head -10)
    if [[ -n "$sdk_matches" ]]; then
        # Show the matching lines with context
        for match in ${(f)sdk_matches}; do
            short=${match#$sdk/usr/include/}
            line=$(grep -n "\b${feature}\b" "$match" 2>/dev/null | head -2)
            echo "    <$short>"
            echo "$line" | sed 's/^/      /'
        done
    else
        echo "    not found in SDK headers"
    fi

    # Try common headers that might declare it
    headers=(
        stdio.h stdlib.h string.h unistd.h
        sys/types.h sys/stat.h sys/time.h sys/resource.h sys/mman.h sys/socket.h
        fcntl.h signal.h errno.h math.h wchar.h locale.h time.h
        dirent.h termios.h pwd.h grp.h
        pthread.h dlfcn.h poll.h sys/select.h sys/wait.h
    )

    # Test as a function
    for h in "${headers[@]}"; do
        cat > "$tmp" <<EOF
#include <$h>
void *p = (void *)&$feature;
int main(void) { return 0; }
EOF
        if $cc -fsyntax-only "$tmp" 2>/dev/null; then
            echo "  FOUND as symbol in <$h>"
        fi
    done

    # Test as a type
    for h in "${headers[@]}"; do
        cat > "$tmp" <<EOF
#include <$h>
int main(void) { $feature x; (void)x; return 0; }
EOF
        if $cc -fsyntax-only "$tmp" 2>/dev/null; then
            echo "  FOUND as type in <$h>"
        fi
    done

    # Check man page
    man_out=$(man "$feature" 2>/dev/null | col -b | head -30)
    if [[ -n "$man_out" ]]; then
        echo "  MAN PAGE: exists"
        echo "$man_out" | grep -iE '(conforming|standard|posix|ansi|iso|ieee|synopsis|include)' | head -5 | sed 's/^/    /'
    else
        echo "  MAN PAGE: not found"
    fi
fi
